### ISSUE TITLE
Do you recommend a CMS for managing JSON?

### ISSUE THREAD

**Issue by laepage** [plentico/plenti#107]
Until the "Edit on page" feature becomes available, which headless CMS do you recommend to manage JSON? I'm thinking primarily of longer texts, blog posts.

**Comment by jimafisk** [comment]
That's a great question, and it's an area where I need to do more testing. I would tend to lean towards a git-cms (like [NetlifyCMS](https://www.netlifycms.org/) or [Tina](https://tina.io/)) vs an api-cms (like [Ghost](https://ghost.org/) and [Strapi](https://strapi.io/)) since that's the general direction I'm trying to take Plenti and the there isn't really a good build-time API mechanism yet in core. I'm honestly not sure how well that will work at this point, but if you have time to lead the charge I'd definitely be interested in your feedback. I'll try to rig up an example with NetlifyCMS at some point as well. Thanks!

**Comment by jimafisk** [comment]
Tying this to similar discussion happening here: https://github.com/plentico/plenti/issues/35#issuecomment-763887470

**Comment by jimafisk** [comment]
Just closing some old tickets. The Plenti project has had a built-in CMS for a while now, so folks shouldn't need to pull in third party projects for this.
