### ISSUE TITLE
What about plentiforms ?

### ISSUE THREAD

**Issue by Valexr** [plentico/plenti#132]
You have plans to implement plentiforms in core or like plugin?
& how I can use it now for plenty site?

**Comment by jimafisk** [comment]
The plan is for [plentiform](https://plentiform.com/) to exist as a microservice that you can integrate with a Plenti site, or other SSG (like Hugo, Gatsby, etc). It currently exists as an app with a Go backend and Postgres database that you would host separately. Offering a hosted solution for this, and eventually other microservices, is one path towards monetization that I'm considering. That said, I'm hoping to open source everything we're working on in the Plenti ecosystem so folks always have the option to run their own infrastructure if they'd like. It's going to be ways down the road before Plentiform is ready because all our effort is focused on making Plenti better, so for now unfortunately it's not ready for use and I've actually made the repo private, but it lives in this namespace: https://github.com/plentiform.

**Comment by Valexr** [comment]
I see... tx🤓

**Comment by jimafisk** [comment]
Np! Feel free to reopen if you have follow up questions, thanks!
