### ISSUE TITLE
"svelte": "^3.32.1" Could not add svelte compiler:

### ISSUE THREAD

**Issue by Valexr** [plentico/plenti#138]
After update SvelteJS to 3.32.1 version & `plenty build`

errs.go:8: Could not add svelte compiler: ReferenceError: require is not defined
Please create a valid Plenti project or fix your app structure before trying to run this command again.
Error: runtime error: invalid memory address or nil pointer dereference

**Comment by jimafisk** [comment]
Thanks for the bug report @Valexr, I see this too. The newer versions of Svelte introduce a few things we need to preprocess in order to run in v8.

On line 22647 of `node_modules/svelte/compiler.js` there's a commonjs require statement `const Url$1 = (typeof URL !== 'undefined' ? URL : require('url').URL);` that we need to remove.

Also starting on line 1673 in `node_modules/svelte/internal/index.mjs` there are a few examples now listed in the comments. Some of our static import regexp was picking up on these, so I updated them to only pull the import statement if its the first character in the line per https://stackoverflow.com/questions/57256550/regular-expression-with-beginning-of-line

It would be great if we could pull newer versions of Svelte in a more predictable way, but it's being written for a NodeJS environment and we unfortunately don't have all of those tools in V8go.

**Comment by jimafisk** [comment]
Should be all set in `v0.3.17`: https://github.com/plentico/plenti/releases/tag/v0.3.17
