### ISSUE TITLE
import ... -> ... is not defined

### ISSUE THREAD

**Issue by j2l** [plentico/plenti#164]
Hi Jim,
I successfully run svelte and three (not svelthree here), but for any reason working code in index.svelte like:
```
import * as THREE from 'three';
const scene = new THREE.Scene();
```
plenti serve throws:
```
Can't render htmlComponent: ReferenceError: THREE is not defined /home/runner/work/plenti/plenti/cmd/build/data_source.go on line 307

javascript stack trace: ReferenceError: THREE is not defined
    at create_ssr:36:16
    at Object.$$render (create_ssr:1555:22)
    at create_ssr:35:135
    at $$render (create_ssr:1555:22)
    at Object.render (create_ssr:1563:26)
    at create_ssr:1:58
```
What does Go need?
Thanks :)

**Comment by jimafisk** [comment]
Hi @j2l, I'm sorry for letting this issue sit for so long without response. I had actually started to respond but needed to fix some bugs before I could get this working.

<details>
<summary>Response I started with webpack instructions (don't use)</summary>
<br>

It looks like [three.js](https://github.com/mrdoob/three.js/) doesn't ship with `.mjs` files by default: https://github.com/mrdoob/three.js/issues/19830. Newer versions of node support this, but our "gopack" (like [snowpack](https://www.snowpack.dev/), but with less features) tool specifically looks for these file extensions for esm support. Down the road I'd like to move the core files from gopack into our ejectable filesystem (https://github.com/plentico/plenti/issues/159) and potentially add esbuild to allow a minimal config setup for pulling in other packages (https://github.com/plentico/plenti/issues/28#issuecomment-678816188).

For now, it probably makes sense to use a bundler like webpack outside of plenti's build process. 
1. Install webpack: `npm install webpack webpack-cli --save-dev`
2. Create `webpack.config.js` in the root of the project with the following contents:
```js
const path = require('path');

module.exports = {
  entry: './node_modules/three/src/Three.js',
  output: {
    path: path.resolve(__dirname, 'assets'),
    filename: 'bundle.js',
  },
};
```
3. Run webpack: `./node_modules/webpack/bin/webpack.js`
4. Reference the newly created file inside `<head>` tags of `layouts/global/head.svelte`:
```html
<script type="module" src="/assets/bundle.js"></script>
```

Then in between the `<script>` tags of your component (for example `layouts/content/index.svelte`) you could import the module like so: 
```js
import * as THREE from '/assets/bundle.js';
```

However doing this ^ gives me an error along these lines:

```
errs.go:57: Can't render htmlComponent: ReferenceError: layouts_content__assets_scene_js_createScene is not defined /home/jimafisk/Projects/jantcu/plentico/plenti/cmd/build/data_source.go on line 321


javascript stack trace: ReferenceError: layouts_content__assets_scene_js_createScene is not defined
    at create_ssr:18:20
    at Object.$$render (create_ssr:1555:22)
    at create_ssr:35:135
    at $$render (create_ssr:1555:22)
    at Object.render (create_ssr:1563:26)
    at create_ssr:1:58 (File: /home/jimafisk/Projects/jantcu/plentico/plenti/cmd/build.go, Line: 140)
```

That's because Plenti is seeing the named import to a locally referenced file and is trying to turn it into a "component signature" that we use internally to identify things in V8. I actually still need to fix this bug, so for now it's probably better to import directly from NPM and with the gopack updates I made in v0.4.28 you should be able to pull threejs in now.

</details>

I made some updates to "gopack" which provides esm support for the project, so now you should be able to `npm install three` then do something like:

```js
import * as THREE from 'three';
```

Here's a working example site demonstrating this: https://github.com/jimafisk/plenti-threejs

**Note:** Just make sure you use the newest release [v0.4.28](https://github.com/plentico/plenti/releases/tag/v0.4.28) to get this working
