### ISSUE TITLE
Document purpose of {...content.fields}

### ISSUE THREAD

**Issue by dougwinsby** [plentico/plenti#190]
I was trying to pass a single "meta" object prop into a `head.svelte` component to group things like "author", "copyright", etc. (passing the object instead of each property separately in the `export let` from a spread).

```html
<script>
  export let title, meta, env;
</script>

<head>
...
  <meta name="author" content="{meta.author}" />
  <meta name="copyright" content="{meta.copyright}" />
```

and then call it like this:

```html
<Head title={content.title} meta={content.meta} {env} />
```
The problem is that it would not recognize the `meta` object properties (i.e. author, copyright).

Looking at `public/spa/content.js`, I saw that everything in `index.json` was put under a "**fields**" property (in `allContent`).

I was able to fix the problem by adding `{...content.fields}` to the call:

```html
<Head title={content.title} meta={content.meta} {env} {...content.fields} />
```

(I tried passing `meta={content.fields.meta}`, but that did not work for some reason I don't understand.)

I believe you can normally leave this off of your prop list (in non-global components) because fields are included by this plenti command:

```html
<svelte:component this={layout} {...content.fields} {content} {allContent} {allLayouts} />
```

I think it might be helpful to explain that all content from your json files are wrapped in a "fields" property which is handled by the `{...content.fields}` spread property.

**Comment by dougwinsby** [comment]
This was very helpful!

A bit of background may help: I'm primarily a Delphi (Windows desktop) developer who found Go to be a delight for back-end work. I then found Hugo for creating internal websites and, while it was powerful, I found it overkill for my needs. This took me to Plenti which seemed "just right" for my current task. I do generally like "convention over configuration", so am happy with your approach. I just needed a bit of hand-holding because I'm missing some of the fundamentals Plenti is based on. (I'd never worked with Svelte and my JS experience is light). So, I probably miss being Plenti's target audience... I don't necessarily want a CMS, but I don't know enough (out of the box) to generate something beyond tweaking an existing theme. (Sorry, that was longer than intended!)

Maybe adding something to the "Types" section would be helpful. For example, right after "Single file types" you could have:

### Content Conventions

Any user defined fields in your json files must be accessed by the `content.fields` prop. It is common practice to include {...content.fields} when defining dynamic svelte components to make this easier. This spread operator allows you to access keys defined in your content source directly at the top level of your templates (e.g. {content.title} instead of {content.fields.title}.

The top level content prop has the following defined keys that are available for all content sources:

* `content.pager`
* `content.type`
* `content.path`
* `content.filepath`
* `content.filename`
* `content.fields`

(I'm not sure that is all correct, but something along those lines would have helped me, I think). 

Some of my confusion was also due to the theme I selected (`maxim`). It uses this Head call:

`<Head title={makeTitle(content.filename)} {env} />`

So I assumed you could just add keys to index.json at the top level and use them. But of course, it needs something like this:

`<Head title={makeTitle(content.filename)} {...content.fields} {env} />`

There are other issues I see in maxim (such as remnants that don't belong, and hard-coded html that should be replaced with data-driven code). If I have time, I will make a PR.

PS: As expected,  `meta={content.fields.meta}` did work for me after all.

**Comment by jimafisk** [comment]
Thanks for the thoughtful response @dougwinsby! I appreciate you writing out some proposed documentation, it looks great for the most part, but there's a minor tweak I'll make to `(e.g. {content.title} instead of {content.fields.title}` because that will throw a syntax error. What I meant by "top-level" is when you use the props in your child template you can do:

```svelte
<script>
  export let title;
</script>
<h1>{title}</h1>
```
Instead of:
```svelte
<script>
  export let content;
</script>
<h1>{content.fields.title}</h1>
```

Speaking to a couple of your other points:

> I'm missing some of the fundamentals Plenti is based on. (I'd never worked with Svelte and my JS experience is light). So, I probably miss being Plenti's target audience...

You're exactly the type of developer I'm aiming for. Ideally Plenti will feel like building a simple HTML / CSS / JS website but with super powers. The JS ecosystem these days can feel complicated with all the tools you typically need to cobble together to make an app. I'm trying to move away from that model and focus on simplicity over extensibility and have as few dependencies / programming conventions as possible. But of course we're using a lot of existing tools under the hood and we're not quite there yet, but that's the goal.

> So I assumed you could just add keys to index.json at the top level and use them

You should be able to add a `title` key to your `index.json` file and then do something like this: `<Head title={content.fields.title} {env} />`. Just keep in mind that if you don't add a `title` key to your other content sources, you'll just need to check that it's available before using it, or it might throw errors.

> There are other issues I see in maxim (such as remnants that don't belong, and hard-coded html that should be replaced with data-driven code). If I have time, I will make a PR.

PRs always welcome! A lot of the themes at http://github.com/plenti-themes were ported from other systems (some rather quickly), so they may need some work to iron out the kinks.

Also thank you very much for sponsoring the project, you're a hero :tada:

**Comment by jimafisk** [comment]
I've updated the document for this: https://plenti.co/docs/types/. I might eventually move the spread operator / dynamic component stuff under https://plenti.co/docs/layouts because it seems like it might be more appropriate there. @dougwinsby thanks again for writing the copy for this! Eventually I'll revamp the content structure for https://github.com/plentico/plenti.co so it's easier to make edits through the CMS.

**Comment by jimafisk** [comment]
Just moved the spread operator / dynamic component info: https://github.com/plentico/plenti.co/commit/3515c7e1bc83bc088a51db17ff0f093f91ac7369

I put this in the layouts section: https://plenti.co/docs/layouts
