### ISSUE TITLE
Media and static folders (robots.txt)

### ISSUE THREAD

**Issue by notramo** [plentico/plenti#226]
How to create a `robots.txt` file on a Plenti site without copying it each time into `public/`?

**Comment by jimafisk** [comment]
Great question @notramo, there currently isn't a native way to do this without rigging up something yourself. We could add a specially named folder `_root` that would simply copy files from the source to the destination: `content/_root/robots.txt`

We could just look for non `.json` files in `content/` and copy those over without requiring a `_root` folder, but there could be an instance where you want to actually copy a JSON file over and not use it as a content source for the SSG, so I think having a special folder makes the most sense. 

I could see the need to copy over other arbitrarily nested files, so maybe naming this folder something like `_copy` would make more sense:
- `content/_copy/robots.txt`
- `content/_copy/somedir/somefile.whatever`

I'll think through the naming a little more, but would something like that work for you?

**Comment by notramo** [comment]
What about making `assets/` available at the site root?

**Comment by jimafisk** [comment]
This is a great suggestion, and I like the idea of allowing people to set their own asset path (whether `/` or `/assets/` or something else) via the `plenti.json` file. However, the media management in the CMS often looks for the `assets/` folder specifically for discoverability.

Hugo uses both `assets/` and `static/` folders, although for a slightly [different purpose](https://discourse.gohugo.io/t/are-assets-and-static-folders-interchangeable/36778). We could probably introduce something similar.

**Comment by notramo** [comment]
Does the CMS looks for `/assets` in the deployment or in the source code?

**Comment by jimafisk** [comment]
Currently both. The CMS by default is "discoverable" (or [contextual](https://twitter.com/jimafisk/status/1519051003202572291)) - meaning that you get an editing interface with different field widgets without having to define these yourself. It just looks at your JSON content source and tries to _discover_ what you might want.

This video is a little outdated, but it shows how an early implementation of how the media browser used the "assets" prefix to provide an image swapping widget: https://youtu.be/0roslBOgk5E?t=847

We do now allow `_schema.json` config files to override the discoverable field widgets: https://youtu.be/wje7VzE7BXE. You can do this at the component level as well: https://youtu.be/zPL8xrS9bVg?t=108. So we could potentially allow users to set their asset path to the root and then they would just need to implement the schemas themselves. 

The tricky part is we'd have to keep track of path that we're saving the file to separately from the path we're rendering the file from. It could get complicated since this spiders out into several different aspects of the CMS workflow. It's a noble goal, and I like the flexibility it would afford, but in the short term I'll probably opt for simplicity while we smooth out some of the rougher edges of the current CMS workflow.

The simplest solution for the time being would probably be to add a `static/` folder. I had a "TODO" to pull some things out of the media browser anyways (like the `global.css` file, favicon, site logo, and other theme files that shouldn't be changed by content editors). It might make sense to also rename the `assets/` folder to `media/` so it not only matches the link in the admin menu, but is a better name in general for the type of content that belongs there. From [sandvox](https://www.karelia.com/support/sandvox/help/z/Media.html):

> The term "media" refers to any files that you might add to a site for visitors to experience: images, movies, music, PDFs, etc.

**Comment by notramo** [comment]
If simplicity is a goal, then I think the better approach would be to split assets into two categories: CMS-managed, and source code assets. E.g. a CMS uploaded image would go to `media/`, but an SVG icon used in HTML would go to `assets/`.
The two folders would have different rendering paths: `media/` would go to `/media/`, and `assets/` would be copied at the site root.

**Comment by jimafisk** [comment]
@notramo that's exactly what I'm thinking, split this into two folders: `media/` and `static/`

The `media/` folder would do what `assets/` does currently with the CMS, it would just be renamed to be more clear.

The `static/` folder would not hook into the CMS at all and would be used for theme related files like global.css, robots.txt, [custom 404 pages](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/43841#note_61584349), or SVGs used in headers/footers, etc. These files would get copied over as-is, directly to the site root.

I think we're saying the same thing, I'm just proposing using `static/` instead of `assets/`, which seems to be the convention of [Hugo](https://gohugo.io/content-management/static-files/), [Docusaurus](https://v1.docusaurus.io/docs/en/site-preparation), and [Nuxt](https://nuxtjs.org/docs/directory-structure/static/). Many of these projects also have an `assets/` folder, but they are typically using that for an "asset pipeline" or source files that are processed in some way before output. We wouldn't be doing that in this case, since most of those tasks are handled by Svelte components directly.

**Comment by jimafisk** [comment]
There are now separate `media/` and `static/` folders in [v0.6.0](https://github.com/plentico/plenti/releases/tag/v0.6.0)

**Comment by notramo** [comment]
@jimafisk, is it backwards-compatible, or is the `assets/` directory completely removed?

**Comment by jimafisk** [comment]
Unfortunately it's not backwards compatible, the `assets/` folder has been completely removed. You'd need to update your content references to use `/media/` instead.
