### ISSUE TITLE
Assets dir in Plenti site template 

### ISSUE THREAD

**Issue by jamestagal** [plentico/plenti#286]
Hi @jimafisk 

Just started on a new theme and noticed that in the ```head.svelte``` file the ```logo.svg``` points to the ```assets``` not the newer ```media``` directory.  See below.

Also not sure whether the first back slash is needed as well but that might only be the case when using a ```baseurl``` setup?

See below.

```svelte
<script>
  export let title;
</script>

<head>
  <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width,initial-scale=1'>

  <title>{ title }</title>

  <script type="module" src="/spa/core/main.js"></script>

  <link rel="icon" type="image/svg+xml" href="/assets/logo.svg">
  <link rel='stylesheet' href='/spa/bundle.css'>
</head>
```
Cheers,
Ben

**Comment by jimafisk** [comment]
Oh good catch @jamestagal! Looks like the `bare` starter was still referencing the old `assets` folder instead of the new `media` folder. I just fixed this, so it should be available in the next release!

You're exactly right about the `baseurl`. If you're using `baseurl`, removing the forward slash from static references lets you serve the entire site from a subfolder. If you're not using `baseurl`, you can just use an absolute or root relative reference with a forward slash. It's more confusing than I'd like, but unfortunately that's how HTML handles baseurls and root relative paths: https://stackoverflow.com/questions/11521011/why-base-tag-does-not-work-for-relative-paths

**Comment by jimafisk** [comment]
Should be all set in [v0.6.21](https://github.com/plentico/plenti/releases/tag/v0.6.21)

Thanks for flagging this to me @jamestagal!

**Comment by jamestagal** [comment]
Thanks @jimafisk and thank you for adding an entry into the docs for [baseurl](https://plenti.co/docs/baseurl). That information really helps.
Cheers,
Ben
