### ISSUE TITLE
Flash of content on page load

### ISSUE THREAD

**Issue by fabian-michael** [plentico/plenti#65]
Loading a site results in a flash of content and thereby a bad cumulative layout shift. I suspect the hydration to be responsible for that.

![Bildschirmfoto von 2020-08-28 13-58-53](https://user-images.githubusercontent.com/26723386/91558462-aab95580-e936-11ea-8893-22124955eef1.png)

Edit: See the second screenshot in Lighthouse where the content is gone

**Comment by jimafisk** [comment]
Thanks @fabian-michael! This has been bothering me too. I think you're right that this is because of how [we're hydrating the page](https://github.com/plentico/plenti/blob/4faa4ad25e1709ba3a78498f37990dc848957dfe/ejected/main.js#L25). I used the model Rich provided [here](https://github.com/sveltejs/svelte/issues/537#issuecomment-298229185) when setting this up. There are probably [better hydration](https://github.com/sveltejs/svelte/issues/4308) approaches out there that I need to look into.

**Comment by jimafisk** [comment]
When compiling we should be setting `hydratable` to `true`.

I think it's put well [here](https://dev.to/gobeli/svelte-prerendering-5579):
> It is important to use the hydratable svelte compiler option for the build of the client code, since we want the client code to hydrate the HTML and not overwrite it.

Per the [svelte docs](https://svelte.dev/docs#svelte_compile):
> If true when generating DOM code, enables the hydrate: true runtime option, which allows a component to upgrade existing DOM rather than creating new DOM from scratch. When generating SSR code, this adds markers to \<head\> elements so that hydration knows which to replace.

Not sure how exactly this will fit in since we're doing the replacement at the `<html>` level and not using a bundler like rollup, but I'm looking into it.

**Comment by jimafisk** [comment]
I have a proof of concept working for this.

I modeled `ejected/main.js` after https://svelte.dev/docs#Creating_a_component:

```js
import App from './App.svelte';

const app = new App({
	target: document.querySelector('#server-rendered-html'),
	hydrate: true
});
```

And made sure to add `hydrate: true` per https://svelte.dev/docs#svelte_compile when compiling the *client* (not the SSR compile). This post was hugely helpful for understanding this: https://github.com/sveltejs/svelte/issues/2901#issuecomment-604124657

Also found [this React discussion](https://stackoverflow.com/questions/46516395/whats-the-difference-between-hydrate-and-render-in-react-16) about `render()` vs `hydrate()` helpful from a conceptual standpoint, the main takeaway being:

> If you call ReactDOM.hydrate() on a node that already has this server-rendered markup, **React will preserve it and only attach event handlers**, allowing you to have a very performant first-load experience.

**Comment by jimafisk** [comment]
Looks like this is nesting top level `<html>` instead of replacing it...

<details>

![nested](https://user-images.githubusercontent.com/5913244/93824104-e6db8f80-fc30-11ea-80e3-08b24754dd84.png)


</details>

**Comment by jimafisk** [comment]
Getting the "parent" of the `<html>` element seems to work:
```js
import Router from './router.svelte';

let target = document.querySelector('#hydrate-plenti').parentNode;

new Router({
  target: target,
  hydrate: true
});
```

Makes me think that we could probably remove the injection of the `#hydrate-plenti` ID completely and just target the `<html>` parent directly. That would simplify some of the build and move us closer to my original vision of allowing the global html wrapper to be more flexible (currently it has to be a file located at `layout/global/html.svelte`, but it would be cool if this was user defined).

<hr>

Not super helpful, but a similar discussion is happening here: https://stackoverflow.com/questions/61640429/how-to-replace-the-contents-of-a-target-in-svelte-instead-of-appending-to-childr

**Comment by jimafisk** [comment]
Console error: 
- Chrome: `Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': Only one element on document allowed.`
- Firefox: `Uncaught (in promise) DOMException: Node.insertBefore: Cannot have more than one Element child of a Document`

**Comment by jimafisk** [comment]
I don't think Svelte was designed to hydrate the `<html>` element, although for the sake of allowing our users to architect everything from svelte templates (as opposed to having to rigged up an index.html file and create an entrypoint), I still think it's the way forward for our project.

Unfortunately you get the same error if you try to explicitly set the anchor:

```js
import Router from './router.svelte';

let anchor = document.querySelector('html');

new Router({
  target: document,
  anchor: anchor,                           
  hydrate: true    
});                                         
```

Related issue: https://github.com/sveltejs/svelte/issues/2573

**Comment by jimafisk** [comment]
The updated hydration should work despite the console error, I guess we just live with that for now `¯\_(ツ)_/¯`

@fabian-michael I just retested with the new [v0.2.37 release](https://github.com/plentico/plenti/releases/tag/v0.2.37), on mobile "cumulative layout shift" seems ok, but it's still flagging it on desktop.

<details>
<summary>Mobile</summary>

![mobile](https://user-images.githubusercontent.com/5913244/93837289-81e56100-fc53-11ea-9280-0b478882abda.png)


</details>

<details>
<summary>Desktop</summary>

![desktop](https://user-images.githubusercontent.com/5913244/93837201-3d59c580-fc53-11ea-90c5-60980db90a17.png)


</details>

I'll have to look into that some more. If you get a chance to retest, can you let me know if the flash of content looks better at least? Thanks!

**Comment by jimafisk** [comment]
There still seems to be an issue around hydrating `<svelte:component this={route} {...content.fields} {allContent} />`. 

Related: https://github.com/sveltejs/svelte/issues/1067

**Comment by fabian-michael** [comment]
Hey sorry for the late reply. I haven't got much time. 
I would really like to help if I had the time, but unfortunately I got too much to do at the moment.

I'll have a look if I find some time.

**Comment by jimafisk** [comment]
No worries @fabian-michael! I did switch out the element replacements we were doing previously for dom repairing hydration, which I think is the better way to go. Unfortunately I think some of the same issues we were experiencing previously are still there, so feel free to hold off testing. This appears to be an ongoing Svelte bug that the community is trying to work out, hopefully more on that soon.

**Comment by jimafisk** [comment]
https://github.com/sveltejs/svelte/issues/5470

**Comment by jimafisk** [comment]
Comment from [Baltimore Go](https://www.meetup.com/BaltimoreGolang/events/twgcdqybcnbjb/) about potential cause of flash of content:

<details>
<summary>Click to see screenshot</summary>

![Screenshot from 2020-10-06 20-45-54](https://user-images.githubusercontent.com/5913244/95385117-8c426480-08bb-11eb-9b0d-8ca956335901.png)


</details>

I think this is a separate issue that also may be happening, if you throttle your connection you might see a brief loading of unstyled content. Svelte has the option to export to a stylesheet or include with JS class: https://github.com/sveltejs/svelte/issues/3604#issuecomment-533810516

The main issue I'm observing is the elements created by `<svelte:component>` are briefly removed entirely during hydration.

**Comment by jimafisk** [comment]
This does not appear to be the hydration issue I thought it was. I ended up pulling down the [svelte fork with better hydration](https://github.com/wix-incubator/wix-svelte), but still had the same problem where the dynamic component was being removed. I also was having trouble replicating this issue in a [non-plenti project](https://github.com/jimafisk/svelte-dynamic-components). 

After a little more digging, it seems the issue is related to how we're getting the `route` value that's used as `this` for the dynamic component. In a new plenti project if you simply hardcode that value, the removing and re-adding of the element disappears. Here's an example of the `layout/global/html.svelte` updates you'd have to make for the homepage to work properly:
```svelte
<script>
  import Index from '../content/index.svelte';
  export let route, content, allContent;
</script>

<svelte:component this={Index} {...content.fields} {allContent} />
```

**Comment by jimafisk** [comment]
I have a working model for this now that fixes the CLS on initial load: https://github.com/plentico/plenti/commit/1eccf048e2a8ffa4c36e6e4555f42753557626cf. Big thanks to @lukeed for helping me work through the routing setup!

There is one more issue I have to resolve unfortunately before pushing out a release. The [insertBefore error](https://github.com/plentico/plenti/issues/65#issuecomment-696443502) previously was just polluting our console logs, now that I've reworked the router to stop the flash of content it makes every page 404 (unless I edit `node_modules/svelte/internal/index.mjs` directly). I've opened an issue with full diagnosis of the problem here: https://github.com/sveltejs/svelte/issues/5547

**Comment by jimafisk** [comment]
I ended up [reworking this a bit more](https://github.com/plentico/plenti/commit/9eb76640f8d2284bc0db419dafc6ba6af6397639). I had previously combined the router and the entrypoint, but that was causing flashes of unstyled content when navigating through client routes. It was hydrating the full dom on every route (including the `<html>` wrapper, `<head>` etc), which was more work than we needed to do, since we really want to just swap out the dynamic content and leave the "global" markup unchanged after the initial page load. It seems to be working better with regards to the Cumulative Layout Shift (CLS) issue:

<details>
<summary>CLS Screenshot</summary>

![lh](https://user-images.githubusercontent.com/5913244/96630701-61a4d280-12e3-11eb-97b7-cf1a8f2b6562.png)


</details>

This still needs a modified `node_modules/svelte/internal/index.mjs` for the `document` replacement issue. It also seems to work pretty consistently in Firefox, but I still notice some style flashes in Chrome at times.

**Comment by jimafisk** [comment]
The newest release (`v0.2.39`) should fix the issue of dynamic components being removed during hydration: https://github.com/plentico/plenti/releases/tag/v0.2.39. 

Note if you're coming from an older version of plenti and want to test the new release, check out this issue so it doesn't break your site: https://github.com/plentico/plenti/issues/76

If folks continue to notice flashing content, please reopen this ticket. Thanks!
