### ISSUE TITLE
Integration with PostCSS and Tailwindcss

### ISSUE THREAD

**Issue by sanderjson** [plentico/plenti#71]
Hello,

I am curious what the best approach is for integrating PostCSS and Tailwindcss. I know in Hugo they have implemented pipes so Hugo can process css files with PostCSS. I think this CSS processing and purging of unused styles would really benefit from being handled by Go.

**Comment by jimafisk** [comment]
Great questions @sanderjson! 

So you could obviously add [tailwind via a cdn](https://tailwindcss.com/docs/installation#using-tailwind-via-cdn), but you lose a lot of the customization options. If someone still wanted to try that, just add the following to `layout/global/head.svelte`:
```
<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
```

I assume you want to be able to customize the default theme and directives though. Do you want to use tailwind completely outside of Svelte's existing scoped styles? 

For that, you're going to want to install with npm:
```
npm install tailwindcss postcss-cli
```

**Note:** If you extend the default npm packages, you have to manage this on your own (like most javascript projects). Plenti will respect an existing `node_modules/` folder in your project, but you need to communicate with your team that they should run `npm install` after pulling upstream changes and you also have to use a container with NodeJS to run your CI builds (add an `npm install` step before you try to `plenti build`). 

Then create a `postcss.config.js` file in the root of your project:
```js
module.exports = {
  plugins: [
    require('tailwindcss'),
  ]
}
```

Also in the root of your project, make an arbitrary folder to hold your tailwind source styles. You could simply put these in your assets folder, but there's no need to include the source styles in your build, we only want the output they create. For this example I'll create a folder called `css` and and put a file called `pre-tailwind.css` inside it with the following content:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Then in your `package.json` make sure to remove the `"type": "module",` line. Then add something like:

```json
"scripts": {
  "build": "postcss css/pre-tailwind.css -o assets/post-tailwind.css"
},
```

Finally make sure to include the CSS output in your project. So in `layout/global/head.svelte` add:
```html
<link rel='stylesheet' href='/assets/post-tailwind.css'>
```

Now you can just run `npm run build` to compile your tailwind styles to the output. If you make adjustments to your source `css/pre-tailwind.css` you will have to do this manually each time.

From there you should be able to adjust your markup to include tailwind utility classes. For example try adding `class="text-4xl"` to some text in your `layout/content/index.svelte` file.

Does that help you accomplish what you were hoping to do, or do you need something more integrated? Thanks!

---

Just another quick note, if using Svelte's default scoped styles, it should already be purging unused styles in the CSS that's shipped to the browser: https://github.com/sveltejs/svelte/issues/697

**Comment by sanderjson** [comment]
Hey @jimafisk  thank you for this detailed and thorough response. I should have mentioned that I am already fairly well versed in a svelte + tailwindcss setup. 

What I am most interested in is the possibility of moving some of the "purging styles" work to Go. I feel this process is a 'slow' step, and thus would really benefit from the inherent language speed. 

I am not well versed in Go, or really in multi language builds yet. But I am very interested in learning.

**Comment by jimafisk** [comment]
Oh ok, that's great because I'm not very well versed in tailwind but I know a lot of people like it! How's the purging normally done, [like this](https://tailwindcss.com/docs/controlling-file-size#removing-all-unused-styles)? I think in order to do that someone would have to rewrite [PurgeCSS](https://purgecss.com/) in Go.

Plenti definitely gets a performance bump by using Go to do things like create scaffolding and read config. However, the bottleneck is compiling Svelte components because even though we don't require nodejs to be installed, we're using v8go to interpret JS which isn't really faster. So even if we leverage Svelte somehow to do this purging for us, I'm not sure if Plenti will be able to speed that process up much. It really would have to be a purpose built tool in Go, but if I'm wrong I'd be happy to take another look. I know Hugo [allows purgecss](https://discourse.gohugo.io/t/optimizing-css-remove-unused/18863) via pipes, but I assume this suffers the same performance issues?

**Comment by laosb** [comment]
I agree that something like PurgeCSS should have a version rebuilt in Go. More than that would be putting this purging step to the last step, making it run after whole JS building procedure, thus benefitting every Plenti site build with no unused CSS shipped to user.

**Comment by sanderjson** [comment]
I found this - may be helpful:

https://github.com/leeoniya/dropcss
(https://news.ycombinator.com/item?id=20654980)

**Comment by jimafisk** [comment]
Seems like folks can use projects like dropcss to speed up their style purging when using tailwind. Plenti most likely will not build a custom style purger in the short term since we benefit from svelte's default removal of unused styles and things like dropcss exist to accomplish this. Thanks for the discussion and resources!
