### ISSUE TITLE
Live reloading

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#99]
@brikou's first impression of lack of hot reloading:

> I've updated `foo/layout/content/index.svelte` to see a change... but I miss hot reload. Let's hit F5. Ok it is updated :).
Maybe I can use snowpack to act as a proxy to enable hot reload

I expect others feel the same way. It might be difficult with Plenti's custom architecture to rig this up yourself with snowpack, but if anyone knows how to do it, I'd love to hear about it. This is something I'd like to see in the project eventually, but it's low on my priority list at the moment.

**Comment by ffmiyo** [comment]
I think this could be done with https://github.com/loov/watchrun.
At a glance the implementation would be; Inject ` <script src="/~watch.js"></script>` into build with `-hmr` argument and monitor public folder.
Is this feasible?

**Comment by jimafisk** [comment]
Watchrun looks like a cool project, thanks for sharing @ffmiyo! I think this might be doing what [fsnotify](https://github.com/fsnotify/fsnotify) is currently taking care of for us (watching for changes on the filesystem and kicking off a new build when one is observed). The next step would be to create a connection from the browser’s web socket client to our local Go server so it can reload the browser silently when those changes are detected. I'm not sure Watchrun can help with that particular aspect, but it's possible I'm not understanding the full extent of its features.

Hugo uses [livereloadjs](https://github.com/livereload/livereload-js) to accomplish this: https://gohugo.io/getting-started/usage/#livereload. We could inject a script for this on local builds, but I'd probably take the opposite approach of Hugo where this is enabled with a flag (e.g. `--livereload`) rather than enabled by default and disabled with a flag (`--disableLiveReload`).

**Comment by padraicbc** [comment]
[This branch](https://github.com/padraicbc/plenti/tree/reload/) has a basic implementation in place. `plenti serve -H` will enable a refresh on save.  The trickiest part is events firing in quick succession ( i.e hitting ctrl-s repeatedly)  and files getting removed/recreated during a reload. It can leave the view broken requiring a manual reload to get it back again.  Not sure what the best approach is really.
 A lot of files are getting rebuilt each time outside of the one actually saved/changed so it may be worth looking at incremental changes based on actual files with new content. That will reduce build times in production especially with large sites.

**Comment by jimafisk** [comment]
This is amazing, thanks for working on this feature @padraicbc! Is that something you could put into a PR, or do you think it's better to resolve the partial build issues you mentioned first? Incremental builds would be awesome, and that would be something we'd want to do at some point for scale so I created an issue here: https://github.com/plentico/plenti/issues/130. I also think our build process could be a ton faster if we started compiling components in separate go routines (https://github.com/plentico/plenti/issues/26) and move some things to a virtual filesystem (https://github.com/plentico/plenti/issues/81).

**Comment by padraicbc** [comment]
No worries.  I created a pull request for  [this branch](https://github.com/padraicbc/plenti/tree/hotreload). The PR has a few notes and there are comments in the code explaining some of the decisions. It will likely change when the build is split into concurrent parts but should do the job for now.

**Comment by zaydek** [comment]
Thought I would drop in to comment that implementing live reload is actually really easy with SSE (server-sent events) and requires very little overhead to get working. Basically, the idea works like this:

On the client (JS), you add a script tag to the bottom fo the rendered page that looks like this: `const events = new EventSource("/events")`. Then you can add event handlers that listen for custom events like `reload`, `error`, whatever you want. On the backend (Go), you can easily emit events using a couple of lines. The nice thing about this architecture is that it doesn’t rely on sockets / libraries as SSE are an HTML spec that has general browser adoption. The only real limitation I’ve ran into is that SSE only propagates to 5-6 tabs maximum (which is fine for most use-cases) because of some limitation with HTTP 1.1 if I remember correctly.

Minimal implementation looks like this: https://github.com/zaydek/esbuild-watch-demo/blob/master/watch.go#L34.

I don’t know if you’re still relying on esbuild or not but esbuild recently implemented a very smart watch mode that looks at your sources and triggers an incremental rebuild when a given source file changes. I don’t know if this works well for what you’re building here, because maybe your requirements are different, but I thought I’d just put that out there.

Is the current implementation HMR or live reload? HMR as in when state is persisted between refreshes, live reload as in hard reloads (but the user doesn’t have to do hit reload themselves).

**Comment by padraicbc** [comment]
HI @zaydek, that looks interesting. Especially `r.Context().Done( )` working. How does it broadcast to all and know when the tabs/browsers have all reloaded? Currently the app is completely rebuilt on any change, even if you just `ctrl-s` without any changes as there is nothing stored and compared etc.. There can only be one buiild running and all connections have to be reloaded before we can allow the next scheduled build to happen. If not then files will get clobbered and break the app as directories get emptied and files get recreated each time. 

`fsnotify` triggers the build so we know when something has been `saved/created/deleted`.  We can use that information to implement #130. 

It is live reload until the full build gets separated out sp we can implement incremental mentioned above and in #26.

**Comment by zaydek** [comment]
I’m interested to hear how you plan to attack HMR. So far I’ve found HMR to be a pretty messy problem so I basically haven’t bothered. I’d love to have my mind changed.

So server-sent events are largely orchestrated for you. From my experience, you don’t need to manage it / broadcast, etc. because the burden falls on browser vendors to implement SSE for you, whereas sockets as far as I understand are a way to hijack connections, therefore the burden falls on you -- the developer or the package you use, to implement it correctly.

> Currently the app is completely rebuilt on any change, even if you just ctrl-s without any changes as there is nothing stored and compared etc.

I believe this is how it works in esbuild-land too, though I’m not sure whether idempotent saves trigger a reload.

**Comment by padraicbc** [comment]
>  I’m interested to hear how you plan to attack HMR. So far I’ve found HMR to be a pretty messy problem so I basically haven’t bothered. I’d love to have my mind changed.

I haven't honestly given it a great deal of thought yet. The incremental/partial builds are definitely higher priority for me anyway.

When you have multiple device/tabs/browser the communication has to be 2-way. You need to keep a record of all the listeners and know when they have completed the reload. If you don't then you have a race condition between finishing the refresh/reload and startng the next build as directories/files get removed so what the browser requests will no loner be there.
If you remove the atomic lock logic or don't wait untill all have reported as reloaded in the hotreload branch code, open a few tabs and hit ctrl-s a few times in quick succession you will see what I mean.

**Comment by zaydek** [comment]
Hey @padraicbc, thanks. Do you have a methodology for persisting state between reloads?

**Comment by padraicbc** [comment]
> Hey @padraicbc, thanks. Do you have a methodology for persisting state between reloads?

Hi @zaydek, I suppose there are a few different approaches depending on what you are using. Sending data back to the server is easy enough as is knowing where to send it back to if you are keeping track of the connections. You could store a unique id in sessionstorage and pass that back and forth to know who/what state you are dealing with. Using an in memory filesystem for  and doing partial builds would also probably make it a lot easier keep track of everything.

**Comment by jimafisk** [comment]
Live reload is available in `v0.3.17`: https://github.com/plentico/plenti/releases/tag/v0.3.17

Use: `plenti serve --live-reload` or `plenti serve --L`

Awesome work @padraicbc :clap: :clap: :clap:
